"""Initial Migration

Revision ID: 664a5612d866
Revises: 
Create Date: 2022-01-05 13:04:48.531479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664a5612d866'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('cust_zip', sa.String(length=10), nullable=False))
    op.add_column('customers', sa.Column('cust_city', sa.String(), nullable=False))
    op.add_column('customers', sa.Column('cust_phone', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('cust_email', sa.String(), nullable=False))
    op.drop_constraint('rawpicts_rp_ep_id_fkey', 'rawpicts', type_='foreignkey')
    op.create_foreign_key(None, 'rawpicts', 'endpicts', ['rp_ep_id'], ['ep_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rawpicts', type_='foreignkey')
    op.create_foreign_key('rawpicts_rp_ep_id_fkey', 'rawpicts', 'cameras', ['rp_ep_id'], ['cam_id'])
    op.drop_column('customers', 'cust_email')
    op.drop_column('customers', 'cust_phone')
    op.drop_column('customers', 'cust_city')
    op.drop_column('customers', 'cust_zip')
    # ### end Alembic commands ###
